version: '3.8'

services:
  db:
    image: postgres:16.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spacesprotocol_marketplace
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
